# Generated by Django 4.2.1 on 2023-07-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(default='Incomplete', max_length=255),
        ),
    ]
